### ISSUE TITLE
Is autoAllocateChunkSize permitted to be zero?

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#1089]
https://streams.spec.whatwg.org/commit-snapshots/41a968974c91e05b20738f77d0b2731ec7391e92/#set-up-readable-byte-stream-controller

> Assert:​ autoAllocateChunkSize is positive

I understood this to mean that autoAllocateChunkSize must be non-zero, but there's no check on construction that this is the case.

**Comment by domenic** [comment]
This regressed in the Web IDL transition. https://streams.spec.whatwg.org/commit-snapshots/cfcd303a38158e4ec3837d1028158c88d505c35d/#set-up-readable-byte-stream-controller-from-underlying-source contains

> If ! IsInteger(autoAllocateChunkSize) is false, or if autoAllocateChunkSize ≤ 0, throw a RangeError exception.

but this was removed in the Web IDL transition because I thought it was no longer necessary. I forgot about 0.

We should add back in a line specifically for 0.

Bonus fix to make at the same time: add `[$ $]` around the IsInteger in https://streams.spec.whatwg.org/commit-snapshots/41a968974c91e05b20738f77d0b2731ec7391e92/#set-up-readable-byte-stream-controller.

**Comment by ricea** [comment]
Okay, cool. @nidhijaju do you want to take care of the spec change, or should I?

**Comment by nidhijaju** [comment]
Yes, I can do it :)

**Comment by domenic** [comment]
We should probably also switch it to TypeError. Otherwise you get TypeError for <0 (because that's what Web IDL does for [EnforceRange]) and RangeError for 0. Which is a bit silly.
