### ISSUE TITLE
`ReadableStreamDefaultReader.read()` return values

### ISSUE THREAD

**Issue by sbooeshaghi** [whatwg/streams#1117]
Hi! Thanks for all of the work in supporting this API. I would like some help clarifying the `ReadableStreamDefaultReader.read()` return values.

In the [Streams specification](https://streams.spec.whatwg.org/) the `ReadableStreamDefaultReader.read()` returns a `{ value, done }` where `done = false` until the [close step](https://streams.spec.whatwg.org/#read-request-close-steps) where there are no more chunks *and* the stream is closed; this makes `done = true`.

However the [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader) on the `ReadableStreamDefaultReader.read()` appears to indicate that `done` will change from `false` to `true` when "the stream has already given you all its data" and does not specify that the stream must be closed.

My limited experience working with streams (using `Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)` ) indicates that `done` will only return true if the stream is closed, though I believe that returning `done = true` when there are no more chunks (keeping the stream open) may be a more intuitive design choice.

**Comment by domenic** [comment]
The spec is correct and MDN is incorrect. I hope this helps!

**Comment by sbooeshaghi** [comment]
Thank you for the clarification!

**Comment by MattiasBuelens** [comment]
> though I believe that returning done = true when there are no more chunks (keeping the stream open) may be a more intuitive design choice

When there are currently no chunks available for reading but the stream is not closed, the promise returned by `reader.read()` will remain pending until either a chunk becomes available or the stream becomes closed. This matches the semantics of the (async) [iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol), so it works well together with other JavaScript APIs.

I understand that it may be desirable to inspect whether there are any chunks already available in a stream's queue. Unfortunately, there's currently no API for that...

**Comment by sbooeshaghi** [comment]
@MattiasBuelens  Determining whether the stream's queue has chunks available is precisely the issue I am trying to solve. Are there plans for adding this functionality? A method like a `streamReader.good()` ([as is implemented in the c++ standard library](https://en.cppreference.com/w/cpp/io/basic_ios/good)) would be useful.

**Comment by sbooeshaghi** [comment]
Sorry, I'm still a bit confused... 

If the `read()` method returns `done=true` when there are no more chunks _and_ the stream is closed will the `readAllchunks(readableStream)` function  in the streams spec (reproduced below) return `chunks` only if the stream is cancelled (which executes a stream close)? Or the reader is cancelled? Will it ever return chunks? 

```js
function readAllChunks(readableStream) {
  const reader = readableStream.getReader();
  const chunks = [];

  return pump();

  function pump() {
    return reader.read().then(({ value, done }) => {
      if (done) {
        return chunks;
      }

      chunks.push(value);
      return pump();
    });
  }
}
```

This is especially confusing since the documentation states that no other consumer can cancel the stream:

> Note how the first thing it does is obtain a reader, and from then on it uses the reader exclusively. This ensures that no other consumer can interfere with the stream, either by reading chunks or by canceling the stream.

**Comment by MattiasBuelens** [comment]
The underlying source [enqueues](https://streams.spec.whatwg.org/#rs-default-controller-enqueue) a bunch of chunks. If the stream's reader does not immediately `read()` these, they stay in the stream's queue. So when the underlying source [closes](https://streams.spec.whatwg.org/#rs-default-controller-close) the stream, the reader doesn't see this until it has read *all* of the previously enqueued chunks. Afterwards, the reader observes the stream being closed: its next `read()` returns `{ done: true }` and its `closed` promise resolves.

My terminology might have been a bit inaccurate. When the underlying source calls `close()`, this sets the "close requested" flag. After the last chunk is read from the queue, the stream's state becomes "closed". So you're right: when the stream is in the "closed" state, that always implies that all chunks have been read from the queue. Sorry for the confusion!

And yes, only the reader can cancel the stream. If you call `reader.cancel()`, the stream will immediately throw away all queued chunks and resolve any pending read with `{ done: true }`. But since `readAllChunks()` never calls `cancel()`, the only way a read can become `done` is if the stream becomes closed.
