### ISSUE TITLE
Meta: file bugs for non-browser implementations?

### ISSUE THREAD

**Issue by MattiasBuelens** [whatwg/streams#1141]
Currently, we file bugs with all major browser vendors for every normative spec change, so they are made aware of our changes and can update their implementations. However, the Streams standard is not *only* implemented in browsers. Deno has been shipping their own implementation for more than a year now (since [v0.42.0](https://github.com/denoland/deno/releases/tag/v0.42.0)), and Node.js has just landed an experimental implementation on their development branch (nodejs/node#39062).

Should we take up Deno and Node.js in our process as well? For example, update the [pull request template](https://github.com/whatwg/streams/blob/c5c062a07c65cb2e61e577c8a55bf8d1c69d67ed/PULL_REQUEST_TEMPLATE.md) to require bugs filed with their projects?

**Comment by ricea** [comment]
My understanding is this is a policy question decided why the WHATWG. @domenic what is your take on this?

**Comment by domenic** [comment]
This level of policy is up to the editors. I totally support doing so.

It becomes a bit tricky though because our PR template is standardized and generated through https://github.com/whatwg/spec-factory . So we could update it now but it'd get overridden next time any updates are deployed by spec-factory.

whatwg/url has a similar issue: https://github.com/whatwg/url/pull/525 /cc @annevk @TimothyGu 

So ideally we'd solve this at the spec-factory level. Some ideas:

- Fix https://github.com/whatwg/spec-factory/issues/23 and then use conditionals in the PR template
- Hard-code some logic in https://github.com/whatwg/spec-factory/blob/main/factory.py, maybe driven by https://github.com/whatwg/spec-factory/blob/main/factory.json, for url and streams

**Comment by MattiasBuelens** [comment]
Fixed in #1211.
