### ISSUE TITLE
Handling Abrupt Completions in ReadableStreamDefaultControllerCallPullIfNeeded?

### ISSUE THREAD

**Issue by mgaudet** [whatwg/streams#1161]
All calls to `ReadableStreamDefaultControllerCallPullIfNeeded` are prefixed with !, [which asserts it should never return an abrupt completion](https://tc39.es/ecma262/#sec-returnifabrupt-shorthands). 

However, the [algorithm steps](https://streams.spec.whatwg.org/commit-snapshots/1246ccb6897cdc9e6d10da06506685a374abf4c1/#readable-stream-default-controller-call-pull-if-needed) include an invocation of a user-controlled algorithm: 

> 6. Let pullPromise be the result of performing controller\.\[\[pullAlgorithm\]\]\.

I'm confused as to how we're supposed to handle an abrupt completion of [[pullAlgorithm]]. 

Exploring the SpiderMonkey implementation, it seems at one point there was an algorithm, [`PromiseCall` ](https://searchfox.org/mozilla-central/rev/9dceacf3d761eb91237108ec438d64099a56f442/js/src/builtin/streams/MiscellaneousOperations-inl.h#32-62), which would take an abrupt completion and return a promise rejected with the error; but we don’t seem to have that algorithm in the current spec. I sort of assume the expectation is that we’re supposed to continue doing that, but I don’t follow how I get that from the specification.

**Comment by MattiasBuelens** [comment]
`controller.[[pullAlgorithm]]` cannot return an abrupt completion.

[SetUpReadableStreamDefaultControllerFromUnderlyingSource](https://streams.spec.whatwg.org/#set-up-readable-stream-default-controller-from-underlying-source) sets _pullAlgorithm_ to the result of [invoking](https://heycam.github.io/webidl/#invoke-a-callback-function) `underlyingSourceDict["pull"]`. Because the return type of [`UnderlyingSourcePullCallback`](https://streams.spec.whatwg.org/#callbackdef-underlyingsourcepullcallback) is `Promise<undefined>`, the WebIDL invoke algorithm will go through these steps:

> 14. Return: at this point _completion_ will be set to an ECMAScript completion value.
> 14.4. If _completion_ is an abrupt completion and the callback function has a return type that is not a promise type, return completion.
> 14.5. Let _rejectedPromise_ be ! Call(`%Promise.reject%`, `%Promise%`, «completion.[[Value]]»).
> 14.6. Return the result of converting _rejectedPromise_ to the callback function’s return type.

Indeed, previously we didn't use Web IDL for this, so we had a separate `PromiseCall` helper. But now we leverage Web IDL's conversion logic, and we expect implementers to conform to the Web IDL spec.

**Comment by domenic** [comment]
Darnit, I had that response half typed up!! :)

**Comment by mgaudet** [comment]
Thanks! Issue seems to be [a Gecko one](https://bugzilla.mozilla.org/show_bug.cgi?id=1726595)
