### ISSUE TITLE
Discussion: How should streams handle Explicit Resource Management

### ISSUE THREAD

**Issue by jasnell** [whatwg/streams#1307]
### What is the issue with the Streams Standard?

The Explicit Resource Management proposal (https://github.com/tc39/proposal-explicit-resource-management) is moving forward in TC-39 and implementers are making progress. One thing I'm not sure has been discussed here is how, if at all, the streams spec should implement ERM.

Let's consider `ReadableStream` first. Let's assume that it is decided that `ReadableStream` should be disposable...

Would it support `Symbol.dispose` (sync disposal) AND `Symbol.asyncDispose` or just async dispose? Let's use an example

```js
const rs = new ReadableStream({
  async cancel() {
    // just fake some async activity
    await scheduler.wait(1000);
  }
});

{ using stream = rs }
```

Would we expect that the sync disposer triggers the async cancel algorithm if the `ReadableStream` is still open and readable? Does a sync disposer even make sense in this case or should it always be `await using`?

Does it even make sense to support disposing of the `ReadableStream` like this? If it is, would it just simply be the equivalent of calling `cancel()` with no reason?

Let's consider a reader:

```js
{
  using reader = rs.getReader();
}
```

When the block exits, do we release the lock on the stream or do we cancel the stream via the reader? Releasing the lock is synchronous (suggesting that the sync `Symbol.dispose` would be sufficient) but canceling is async (suggesting that we would need `Symbol.asyncDispose`). 

Let's consider a more complex case (this part may be more appropriate for the fetch repo so if we need to discuss it there, let me know)... Let's assume that the stream is attached to a disposable type, and let's assume that `Response` is defined as disposable... what should we expect would happen to the stream in the following case:

```js
let stream;
{
  using resp = await fetch('http://example.com');
  stream = resp.body;
}
// Is the stream still readable here? Or was it disposed of?
const reader = stream.getReader();  // ??
```

The same basic questions apply to `WritableStream`, of course

```js
const ws = new WritableStream({
  async abort() {
    await scheduler.wait(1000);
  }
});

let writer;
{
  // is sync dispose ok here? will it trigger the abort alg?
  using stream = ws;
  writer = stream.getWriter();
}
// is writer still usable?
```

**Comment by domenic** [comment]
I had always assumed `ReadableStream` would not be disposable, but readers would be, and disposing them would be equivalent to `releaseLock()`.

**Comment by jasnell** [comment]
I definitely think that's the easiest approach to take and definitely has the fewest number of potholes ;-) ... and I'm 100% fine if we go with that, I just want to make sure the options are discussed rather than just assumed :-) 

At least in theory, supporting async disposal of a readable stream *could* be the equivalent to cancel...

```js
{
  await using rs = new ReadableStream({ ... });
}
```

By example, Node.js has implemented this pattern for Node.js streams, e.g.

```js
// a node.js stream, not a ReadableStream
const r = new stream.Readable;
r[Symbol.asyncDispose]();   // cancels and destroys the stream
```

I can see some merit in the approach but I also like the simplicity of just saying, these streams aren't disposable, only the readers/writers are.

**Comment by annevk** [comment]
cc @MattiasBuelens @ricea @youennf

**Comment by annevk** [comment]
It would help if you could link to the proposal in OP here and in #1741.

**Comment by MattiasBuelens** [comment]
I agree that readers and writers should be sync-disposable. Conceptually, the "resource" they're holding is the lock on the stream, so when you dispose them, they should release that resource through `releaseLock()`. This also shows up in other languages, e.g. a Rust [`MutexGuard`](https://doc.rust-lang.org/std/sync/struct.MutexGuard.html) releases its lock on the parent `Mutex` when dropped.

Personally, I would expect readable and writable streams to be async-disposable.
* Async-disposing a `ReadableStream` should `await readable.cancel()`.
* Async-disposing a `WritableStream` should `await writable.close()`. This aligns closer to [the proposal for Node.js Writable](https://github.com/tc39/proposal-explicit-resource-management/blob/06e6070442b7a2bd3bc18730dc78cb7ee9a88130/README.md#nodejs-streams) to use `writable.end()`.

This does mean that anything you do with that stream needs to be *inside* the block with the `await using`:
* If you acquire a reader/writer, you should release it within that block. This should be easy with `using reader = readable.getReader()`.
* If you async-iterate the stream, you should either `await using iterator = readable.values()` so the iterator will properly release its lock when done, or just use `for await (const chunk of readable)` to do that automatically.

Piping is really tricky though. You're almost *required* to `await` every `pipeTo()`, otherwise the stream will still be locked at the end of the `await using` block. I don't even know what we'd do with `pipeThrough()`... :confused:

Oh, and then there's `tee()` which keeps the original stream *locked forever*, so you can never dispose it... 😅

**Comment by domenic** [comment]
The discussion so far has convinced me that we should not make `ReadableStream` disposable. It adds to much complexity for not enough benefit, and encourages bad interactions with tee and piping. And, IMO it's bad practice to call `cancel()` with no argument anyway, and the using syntax does not give a place to insert the appropriate argument.

**Comment by jasnell** [comment]
Heh, I think I managed to convince myself of the same result :-) ... Having readers and writers be disposable so that they release the lock is fine, I think, but even that is probably not critical at all.

**Comment by jasnell** [comment]
Ok, I think given the discussion and after running through a ton of scenarios in which I've failed to convince myself that it could work, I think we've hit the right conclusion here and will close this issue. I'd say that even making readers and writers disposable is probably not something that is critical at all. Thank you for the consideration on it. I do think we need to have similar conversations and considerations for other web platform apis like `Request`, `Response`, etc, but those are best had in those repos.

**Comment by Josh-Cena** [comment]
So, is the conclusion that the stream API would not integrate with explicit resource management at all? Though making streams disposable seems complex, I think making readers disposable would not be, and the proposal quotes `stream.getReader` as one potential use case anyway, but I didn't find any relevant discussion in this repo.

**Comment by domenic** [comment]
I'd like to make readers and writers disposable, but making any web platform API at all disposable requires a good amount of integration work which nobody has volunteered to do, unfortunately.

**Comment by Josh-Cena** [comment]
So, I guess https://github.com/whatwg/html/issues/8557 is the place to follow then?

I'm trying to look for a sync disposable example (Node `fs.FileHandle` is async) and it's proven quite challenging.

**Comment by jasnell** [comment]
@domenic ... I'm actually happy to do the work on spec text and help contribute to tests as I do think this would be valuable. So if there is definite interest then I think it's worth keeping this open?

**Comment by domenic** [comment]
Sure, I'd be happy to keep this open to track it.

To be clear, the integration work I'm referring to is adding Web IDL support so that these can integrated into the bindings layer. Probably [stringifiers](https://webidl.spec.whatwg.org/#idl-stringifiers) are a reasonable precedent? Although I haven't looked in full detail.
