### ISSUE TITLE
Misuse of `Assert` in spec

### ISSUE THREAD

**Issue by rotu** [whatwg/streams#1327]
### What is the issue with the Streams Standard?

In the streams spec, "Assert:" is used in a way that deviates significantly from the ECMAScript spec. e.g. the `pipeTo` method eventually calls `ReadableStreamPipeTo` which starts with checking caller-provided values.

> 1. Assert: source [implements](https://webidl.spec.whatwg.org/#implements) [ReadableStream](https://streams.spec.whatwg.org/#readablestream).
> 2. Assert: dest [implements](https://webidl.spec.whatwg.org/#implements) [WritableStream](https://streams.spec.whatwg.org/#writablestream).
> 3. Assert: preventClose, preventAbort, and preventCancel are all booleans.
> 4. If signal was not given, let signal be undefined.
> 5. Assert: either signal is undefined, or signal [implements](https://webidl.spec.whatwg.org/#implements) [AbortSignal](https://dom.spec.whatwg.org/#abortsignal).

This usage of "Assert:" can't be consistent with the ECMAScript spec meaning, which indicates a logically entailed invariant[^1]. I believe that most instances in this spec of "Assert:" should actually be changed to throwing a `TypeError`.

[^1]: > A step that begins with “Assert:” asserts an invariant condition of its algorithm. Such assertions are used to make explicit algorithmic invariants that would otherwise be implicit. Such assertions add no additional semantic requirements and hence need not be checked by an implementation. They are used simply to clarify algorithms.

**Comment by MattiasBuelens** [comment]
This specification, like many other web specifications, uses [Web IDL](https://webidl.spec.whatwg.org/) for its interface definitions. Therefore, by defining the parameter types of the `pipeTo` method [in the IDL of section 4.2.1](https://streams.spec.whatwg.org/#rs-class-definition), the Web IDL machinery will perform the appropriate type checks in the JavaScript bindings. Thus, these invariants are in fact fulfilled when `pipeTo` calls `ReadableStreamPipeTo`.

The reason why we still have these assertions is because we also expose [the "pipe to" algorithm](https://streams.spec.whatwg.org/#readablestream-pipe) for use by other specifications (e.g. fetch). In that case, it's the responsibility of the calling specification to make sure the inputs are correctly typed.
