### ISSUE TITLE
TransformStream probably doesn't need two strategies

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#190]
See discussion in https://github.com/whatwg/streams/pull/169#discussion_r16258931.

**Comment by ricea** [comment]
Suppose we want the normal Reader and Writer interfaces to work with TransformStream. `pipeTo()` is defined in terms of those interfaces, so I think we do. Also, it would break the principle of least surprise if you couldn't do `getReader()` on the `readable` and `getWriter()` on the `writable`.

In that case, TransformStream needs two queues. The `writable` queue permits calling `write()` while an async `transform()` is in progress, and the `readable` queue handles the mismatch between the _push_ `enqueue()` interface inside `transform()` and the _pull_ `read()` interface exposed by the Reader.

In general, when a TransformStream is connected to a pipe on both ends, those queues can go away. An important exception is when HWM is infinity on the TransformStream. In this case, the pipe absorbs any amount of backpressure.

In general, if you set HWM to some amount of megabytes or chunks which is larger than the strategy on either side then you get that much caching introduced into your pipe.

I think this is useful behaviour and should be maintained even when using `pipeTo()` (while still short-circuiting the queues as much as possible).

So, I've made an argument for having one strategy, now can I argue for two?

I don't think so.

As far as I can tell, you can get this useful behaviour by setting the strategy on either the `readable` or `writable` side. It doesn't matter which, just don't set it on both.

Now I want to consider what happens when `transform()` is slow. I'm going to call a configuration where the `writable` size has a small HWM and the `readable` size has a large HWM a small/large configuration, and the opposite a large/small configuration.

In a small/large configuration, the Writer has to wait until `transform()` is done before writing more. The Reader also has to wait, just because the data isn't available yet. When `transform()` is the bottleneck, it's no different from small/small.

In a large/small configuration, the Writer doesn't have to wait until the queue fills. For sufficiently small data, the Writer never has to wait at all. The Reader still has to wait for `transform()`.

Even in a large/large configuration, the Reader can read no faster than `transform()` can run. In other words, large/large is identical to large/small.

So, for sufficiently fast `transform()`, small/large and large/small are equivalent. When `transform()` is the bottleneck, then small/large is equivalent to small/small, but large/small provides extra buffering.

I therefore conclude that large/small is the most useful configuration, and therefore it is the `writable` side that should have the configurable strategy.

As a way forward, I suggest we write tests for the above cases and verify that they work as I have described, and then remove the ability to configure the `readable` strategy.

**Comment by isonmad** [comment]
What about when the location of the bottleneck is unstable and changes?

Like if the ultimate sink is an unreliable internet connection or some other sink that's usually rapid in its consumption of chunks, but can have long periods of stalling. And the TransformStream in question has a very heavyweight, slow transform that in ideal operations, would be the bottleneck of the pipe. But when the sink suddenly stalls, that sink becomes the bottleneck instead, and queueing up the results of the slow transform is helpful, as the work is done 'ahead of time' and can be rapidly drained when downstream conditions improve again.

**Comment by ricea** [comment]
@isonmad I hadn't thought about that.

My initial thought is that if the sink is badly behaved, the queuing belongs inside the WritableStream for the sink rather than inside the TransformStream. However, I'm prepared to be convinced otherwise.

**Comment by ricea** [comment]
What I'd like to do is use the equivalent of `CountQueueingStrategy({highWaterMark: 0})` for the `readable` and then pass the second argument to the TransformStream constructor directly to the WritableStream constructor to be the `writable` strategy. This will make TransformStream simpler to use, simpler to test and simpler to implement.

One thing is holding me back: what if the `transform()` method is "lumpy"?

By "lumpy" I mean that the time it takes is not consistent: sometimes it is fast, and sometimes it is slow. I'm sure someone has a better word for this concept.

When a source is lumpy, the creator of the ReadableStream object can use a strategy with a larger queue to compensate and the consumer of the data will get a smooth flow. Similarly, if a sink is lumpy you pair it with a larger queue and then the user of the WritableStream doesn't have to worry about it. It would be symmetrical if TransformStream had the same property.

However, if the readable side has a HWM of 0 then there will be no "transform ahead" and anything reading from the transform will experience the lumpiness directly.

Making the `readable` strategy configurable and the `writable` strategy fixed is not attractive because a WritableStream has to have a non-zero HWM in order for backpressure to work. Where you have a non-zero HWM it's really good to be able to set the `size()` methods on both sides of the pipe to be the same so that `pipeTo()` can perform a queue-merging optimisation. Also, if the side that's writing to the `writable` experiences lumpiness then that is not good either.

**Comment by ricea** [comment]
My conclusion: sadly we need to keep having two strategies.

**Comment by domenic** [comment]
Maybe we could call one of them strategy and the other readableStrategy, and document that the latter is only useful in specific scenarios?

**Comment by ricea** [comment]
I have an idea that might just work. Instead of combining the strategies into a single argument, how about making them positional arguments? In other words, the constructor would look like

```javascript
new TransformStream(transformer, writableStrategy, readableStrategy);
```

The benefits:
- It pushes people in the direction of using the `writableStrategy` in preference to the `readableStrategy`
- It will usually look like the calling convention for ReadableStream and WritableStream.

Disadvantage:
- People who work with code that actually uses both strategies will have to remember which way around the arguments go.
