### ISSUE TITLE
readable-stream-cancel.js "ReadableStream canceling an infinite stream" is flaky

### ISSUE THREAD

**Issue by calvaris** [whatwg/streams#286]
Sometimes this test can be flaky.

In WebKit, when I translated it, I changed it to reinstate the timeout if we were still waiting, but it is not enough, as you can get the timeout, be in readable state and the readableStreamToArray function didn't have enough time to read any data, so we cancel and we don't read anything.

There I also reduced the timeout to make it faster from 150 to 50 and I wait now to have run the timeout both in readable and waiting or as many as 6 timeout executions, otherwise I reinstate the timeout.

If you think this makes any sense, I could prepare a pull request with these changes.

**Comment by domenic** [comment]
Yes, please feel free to pull request.

In general I would like to reduce the use of setTimeout throughout the suite. The only potentially-legit cases I can think for it are where something should "never" happen (e.g. a promise should never be settled), we could use setTimeout(, 50) or so to check that. Otherwise we should in general save promises more and wait on them (pretty much every setTimeout(, 0) could be replaced by this).

Also: you may be interested in something I recently put together (https://github.com/whatwg/streams/commit/28f9bda6b2a4c4456b939b64f7ad32bdf128c015) that makes the tests runnable against your current browser: https://streams.spec.whatwg.org/tests/ Right now it is kind of tuned for Chrome (e.g. it lets `let`/`const`/iterators/`for-of` pass through instead of transpiling them) but I can tweak that if you can let me know what is supported by the browser you're developing on.

Finally if you're actively implementing you may want to weigh in on #253 where we're having an unfortunately-last-minute-feeling discussion that might end up changing the semantics of read()/ready/state to become an async read() :-S.

**Comment by calvaris** [comment]
I might fix the issue and if I have even more time, I might translate the tests to something more interoperable, like for example, removing the arrow functions that were implemented by a colleague in V8, but they are not in JSC yet.

Btw, as you requested I commented what I could in #253.

**Comment by domenic** [comment]
> I might translate the tests to something more interoperable, like for example, removing the arrow functions that were implemented by a colleague in V8, but they are not in JSC yet.

The arrow functions are transpiled away before deploying the tests, as you can see from https://streams.spec.whatwg.org/tests/bundle.js

> Btw, as you requested I commented what I could in #253.

Thanks very much. I've been swamped on that and related issues for a while but will be trying to work through my backlog today.
