### ISSUE TITLE
Generalized and precise flow/buffer control

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#301]
Before recent redesign, we always had a queue in the JS world behind a readable stream, and we calculated how to exert backpressure to the "underlying source" based on the size of the queue.

We're now separating the streams API semantics visible to the consumer (mainly implemented in the reader) and a queue behind it which doesn't always exist (depending on who (JS, C++ code, kernel, device, etc.) buffers data). This made me think more generally, that is, there're many points of buffering behind streams. The number of such points depends on which API we're using, which platform we're using, etc.

It sounds like both the high water mark & strategy concept, and the precise flow control stuff I proposed only make sense for streams with a queue in JS world. It seems it's hard to well-define `queueSize`, `highWaterMark`, `pullAmount`, etc. as cross-platform, cross-API feature.

To put it differently, for non-JS-queue-backed APIs, what do we guarantee for the consumer when HWM is set to X?

I still guess some kind of best-effort approach is still useful. The UA tries to keep the number of bytes buffered on the path between the ultimate data source (disk, the peer server, etc.) and the JS world. As Domenic originally suggested, the strategy itself should be chosen intelligently by the UA considering memory size, CPU power, browser architecture, etc. etc. and it's responsible only for computing how much data is buffered in **the JS world**. Combining buffer size info (C++, kernel, JS, ...), the UA would intelligently limits the amount of data to pull.

And, the `pullAmount` or something in the proposed precise flow control APIs will just give a hint about how quickly the consumer can consume data in the form of the number of bytes. It is not directly connected with such as the size of the queue in JS. The stream utilizes the info using some algorithm to control amount of data to pull.

**Comment by tyoshino** [comment]
As Yutaka has been advocating, we should stop attempting to specify direct connection between the "underlying source" which the JS code faces and the readable (byte) stream operation. Not directly, but just have a good API surface that **could** be utilized for optimization if the implementor of the readable (byte) stream wants. Bring your own buffer style reader allows the implementor to directly connect `read(view)` with ReadFile, etc, but it's not required. As we discussed offline, the JS library may be requested to drain data from underlying source into an ArrayBuffer in JS given some consuming pressure. In such case, we don't pass the view provided by the consumer to ReadFile, but copies data already read out to the provided view.

**Comment by domenic** [comment]
I agree with the first post. In https://github.com/whatwg/streams/issues/294#issuecomment-81557090 I summed it up in terms of a proposed `.getReader({ queueSize: x })` API. And yeah, it is best-effort, with the underlying source implementation taking it into account to decide what to actually do.

On the second post, I also agree that there should be no necessity of connecting the view directly to ReadFile or similar. But just in case it wasn't clear, I think it's important to design the stream + underlying source constructor parameter combo so that you *could* code the underlying source purely in JS. That is, let's say we had almost-direct JavaScript bindings of syscalls (like [this for files](https://blog.domenic.me/reading-from-files/) or [this for sockets](https://blog.domenic.me/reading-from-sockets/)). Good underlying source code would still have to do more work, e.g. if the socket buffer is overflowing then the underlying source needs to copy into user-space and then later instead of reader.read() going directly to the syscall it copies the previously-saved buffer. But the important thing is that you could in theory express it all in JS using the underlying source constructor parameter + appropriate syscall bindings. So in this world e.g. `underlyingSource.read(view)` would have code to check any previously-copied stuff, and if not would call through to the syscall. Make sense?

**Comment by tyoshino** [comment]
> #294 

Oh, yes. Sorry I forgot to cite that comment.

> I think it's important to design the stream + underlying source constructor parameter combo so that you could code the underlying source purely in JS. ...

Agreed. Thanks for clarification.

**Comment by domenic** [comment]
My current thinking based on discussions this morning:

- pull(enqueue, close, error) becomes pull(enqueue, close, error, spaceLeftGetter) in functionality. (In name and shape, maybe `pull({ enqueue(), close(), error(), desiredSize })`? Can be settled afterward though.)
- Strategies need to be modified to have high water mark directly instead of having flexible shouldApplyBackpressure predicate. (Maybe we allow it to be updated, but unsure by who or how.)
- The when-should-we-call-pull logic stays similar to how it is now, with one addition:
  - After start
  - If queue size changes, up or down, and _either_:
    - spaceLeft = HWM - queueSize > 0, or
    - there are pending reads
  - Promise-debounced

With this change, and a strategy that says HWM = 0, read() will directly correspond to pull(), which is good. (The "if there are pending reads" ensures it.)

With a strategy that has HWM > 0, then pull will be called whenever the queue size is less than the high water mark, and it will be called with spaceLeft (or "desiredSize" maybe) = HWM - current queue size, which allows it to make intelligent decisions about how to generate chunks that it will enqueue.

**Comment by tyoshino** [comment]
Some logs of the last week's discussion
- For the initial release, `read` method is the only way for the consumer to tell the stream how fast the consumer is / how much the consumer is fine with getting buffered. Readable stream doesn't expose setHWM to the consumer.
    - [tyoshino] Re: naming, I prefer pullAmount (or something similar) to HWM as HWM sounds like assuming that there's a queue.
    - [tyoshino] If we add a similar method to the writable side, it should use "space" not "queueSize" for its name. We have many queues behind a writable stream (JS, C++, kernel, device, ...). If we say "queue", we need to tell what the "queue" means and forces the consumer to think of the details behind the writable stream.

**Comment by domenic** [comment]
I'm working on this in the precise-flow-control branch. It's going pretty well. Gotta update some more tests (especially around writable streams) and the spec, but shouldn't be too bad.

I went with `desiredSize` for the name for now. It seems OK. Other candidates included `extraSpace` or `(space|size)UntilFull`.
