### ISSUE TITLE
Extract the minimal algorithm from which we can easily infer the public behavior of the interfaces

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#312]
We've been sporadically saying that we need a definition of the interfaces not by JS code but by describing publicly visible behavior of each property.

I'm trying to build it at:
https://github.com/whatwg/streams/blob/asyncbytestream/BinaryExtension.md

IIRC, @domenic said that the current spec also includes some texts doing this. But I couldn't find it.

**Comment by domenic** [comment]
Hmm, there might be some confusion here.

The current spec does define the interface in terms of its publicly visible behavior. It does so by giving one algorithm that will produce the normatively-required results. But if you have another algorithm that would do so, and is black-box indistinguishable, that is also a fine way of implementing the spec.

For example, the queue-with-sizes data structure is fantastically inefficient as specced. Presumably one would instead keep track of the sizes as things are added and removed from the queue. The key thing is that that behavior is black-box indistinguishable from the behavior specced (which sums up all the sizes every once in a while).

The danger of something like https://github.com/whatwg/streams/blob/asyncbytestream/BinaryExtension.md is that it does not give precision to interactions between different parts of the API, especially things like interaction between the underlying source and the stream's methods, or the sequencing of different events (calling read() twice, etc.). I think the better path is to produce a full algorithmic specification of the methods (and validate the algorithm with a reference implementation), as we have been doing.

From another angle, perhaps the main part of this issue is the idea of how to state invariants and contracts that must apply to all readable streams. That's what I think the templated tests accomplish. We could expand those a bit (to allow porting more existing tests) if we allowed templated "actions", e.g., create a stream, run some test code, then run an action like erroring the stream, then run some more test code.

**Comment by tyoshino** [comment]
The text in BinaryExtension.md is still premature. We of course need to describe that. Actually, the text already includes the state concept to guarantee some invariants, preconditions. So, already not fully blackboxed. In prototyping the thin streams in the operationStream branch, I tried to describe the constraints using thin layer of algorithm. I want to do that in natural language..

It's possible to infer the normatively-required results from what we have in the spec now (with a queue), but I want to try to do more decoupling.

**Comment by tyoshino** [comment]
By "natural language", I mean writing spec texts. I don't mean that we shouldn't write algorithm.

**Comment by domenic** [comment]
Awesome, yeah :). Then the text above it is similar to the notes, e.g. in https://streams.spec.whatwg.org/#rs-get-reader ?

Also tagging in @annevk because we've had discussions on this sort of thing in the past (especially with regard to non-normative notes and how detailed they should be).

**Comment by annevk** [comment]
The only thing I remember discussing is having language to talk about streams *normatively* without having to construct JavaScript objects and such. E.g. language that could replace https://encoding.spec.whatwg.org/#concept-stream and the streams language in Fetch that is not API-exposed.

**Comment by domenic** [comment]
@annevk I meant more in general, e.g. non-normative notes in the DOM spec. (Still not sure about whether this spec seeks to define "conceptual streams"... it's not like we have a definition for "conceptual promises" divorced from JS objects.)

**Comment by tyoshino** [comment]
> Then the text above it is similar to the notes, e.g. in https://streams.spec.whatwg.org/#rs-get-reader ?

Right, if written in natural language. I'm fine with writing algorithm though.

> conceptual promises

It seems the promises algorithm is thin enough as what I'm trying to give for ReadableStream.

**Comment by tyoshino** [comment]
It seems this can be achieved with a little work. E.g., in `ReadableStreamReader.prototype.read()` only the step 6 is specific to the queue-backed type ReadableStream implementation. If we extract this step as an abstract operation say `GenerateChunk()` that returns a tuple of `{ sync, value, done }`, then this algorithm would be:

- ...
- Let _result_ be GenerateChunk(**this**[[ownerReadableStream]]).
- If _result_@[[sync]] is **true**,
    - If _result_@[[done]] is **true**, call-with-rethrow CloseReadableStream(**this**@[[ownerReadableStream]]).
    - Return a new promise resolved with CreateIterResultObject(_result_@[[chunk]], **false**).
- Otherwise, ...

Now, the algorithm is describing all the constraints on how `reader.read()` should behave and interaction with other parts of the interface without saying anything about internal buffering.

POSIX `select`+`read` based ReadableStream may implement `GenerateChunk()` to generate an ArrayBufferView and read(2) and return it synchronously.

**Comment by tyoshino** [comment]
This refactoring is just annoying if put in a text just to define the JS queue-backed ReadableStream. So, trying to figure out where should we do this.

**Comment by tyoshino** [comment]
I was trying to do this in [BinaryExtension.md in asyncbytestream branch](https://github.com/whatwg/streams/blob/asyncbytestream/BinaryExtension.md). I've moved the place to experiment that to PR #343.

**Comment by tyoshino** [comment]
The BinaryExtension.md file in asyncbytestream branch still holds some draft and explainer texts.

**Comment by tyoshino** [comment]
The queuing mechanism in the ReadableStream has been moved into ReadableStreamController. Now the ReadableStream is succinctly representing the semantics required for things that are considered to be valid implementation of the ReadableStream (see the commit log of https://github.com/whatwg/streams/commit/e601d69f3ba40e6f4b5506e4bb1fbe3f3eabf393).
