### ISSUE TITLE
How generic is pipeTo?

### ISSUE THREAD

**Issue by youennf** [whatwg/streams#407]
It is said in https://streams.spec.whatwg.org/#rs-pipe-to that pipeTo can be applied generically to other objects than ReadableStream.
It is not clear though whether pipeTo accepts WritableStream objects only or other objects as well.
I guess it is the latter but would the spec be able to state it clearly like done for ReadableStream?

**Comment by domenic** [comment]
This section of the spec is kind of a mess, I'm sorry.

The intention, per previous discussions in #97, is to have pipeTo actually not be generic. It will only accept true WritableStream objects, and will operate using abstract operations instead of going through the public API. The reference implementation does not yet reflect this.

There's a long dependency chain here unfortunately, such that the proper order is:

- Update writable streams a significant amount, in particular #318 and #319. See also the warning at https://streams.spec.whatwg.org/#ws.
- Then, update pipeTo to work with the new writable stream abstract operations that this will create, and to be non-generic.
- Finally, actually spec pipeTo, instead of having a note saying "please go see the reference implementation for our current best guess."

I'm sorry this isn't ready yet. In general writable streams need more attention. I hope this helps in the meantime, but let me know if perhaps adding a note like this in the spec text would be helpful...

**Comment by youennf** [comment]
Thanks for the information and links.
I guess it is ok to leave the spec as is if pipeTo does not remain in the limbs for too long.
Otherwise, maybe add something like "pipeTo relying on WritableStream abstract operations, it is expected to change significantly" or loosen the statement that the pipeTo reference implementation is considered normative.

**Comment by domenic** [comment]
I've changed the wording a significant bit in the above commit. Thanks very much for bringing this to my attention; the previous wording was pretty off.

I'll work on getting writable streams and pipeTo ready as soon as I can :).

**Comment by youennf** [comment]
"it will not operate via the public readable and writable stream APIs".
Don't you want to say the opposite i.e. pipeTo will operate via public APIs?

**Comment by domenic** [comment]
No. The idea from #97 is that it will not be generic, and will operate using abstract operations instead of going through the public API.

**Comment by youennf** [comment]
Right, I misinterpreted the meaning of public, public to JS not to other specs...
I would have phrased it positively though (it will use abstract streams operations).
Anyway, thanks for the clarification.
