### ISSUE TITLE
Target for web-platform-tests streams API tests 

### ISSUE THREAD

**Issue by youennf** [whatwg/streams#411]
I saw the job done in https://github.com/whatwg/streams/blob/master/reference-implementation/web-platform-tests. This looks very good.

We might want to reuse those tests directly in WebKit.
I was wondering whether you were planning to move all those tests at some point to W3C web-platform-tests repo? If so, do you have any special schedule?

Also, the current html tests are running regular tests, tests in worker, tests in shared worker and tests in service worker. Would it be possible to split them in xx.html, xx-worker.html, xx-sharedworker.html...? If that is ok, I can take over that editing.

**Comment by wanderview** [comment]
I'm going to be starting gecko work on streams soon.  I could get these tests into wpt repo as one of my first tasks.  Unless @domenic want to do it.  I might not get to to it for a couple weeks.

**Comment by wanderview** [comment]
Here is the gecko bug to import and uplift the tests:

https://bugzilla.mozilla.org/show_bug.cgi?id=1230148

It might easier for me to do it this way since we have the infrastructure to execute the tests in automation and then automatically merge the new tests into wpt upstream.

**Comment by jgraham** [comment]
Does nightly webkit have all the ES6 features these tests use? If so, great, if not we might want to replace some arrow functions with normal functions, and whatever else is needed.

This webkit limitation of requirements around the filenames seems like it is going to get pretty tedious pretty fast.

**Comment by wanderview** [comment]
As long as the different worker types are in different test cases, can't you just mark the SharedWorker and ServiceWorker cases expected fail in webkit?  Separate file names seems excessive.

**Comment by youennf** [comment]
I think @calvaris tested that ES6 used features are fine in WebKit nightly.
As of different tests files, it is ok if some sub-tests pass and others fail.
Test should just not time out or not be able of executing in case of missing serviceworker/sharedworker. Let me check that.

**Comment by calvaris** [comment]
ES6 syntax used by the tests is supported by WebKit. As @youennf says workers (at least not fully, I haven't checked either) are not.

**Comment by wanderview** [comment]
> Test should just not time out or not be able of executing in case of missing serviceworker/sharedworker. Let me check that. 

I think wpt infrastructure lets you disable tests if you prefer instead of marking expected-timeout.

**Comment by domenic** [comment]
@youennf

> I was wondering whether you were planning to move all those tests at some point to W3C web-platform-tests repo? If so, do you have any special schedule?

That's definitely the plan. The tests have lived here historically because they evolve in concert with the spec, and I like being able to make changes in a single commit. But, maybe these parts of the spec have stabilized enough that I should upstream them and stop maintaining a copy here.

Maybe one way to allow me to maintain my workflow would be for web-platform-tests to have a submodule dependency on whatwg/streams? But, maybe that is too much special-casing just for me, and could cause problems for other tools like e.g. the Mozilla tooling @wanderview mentions. On the other hand, I think more specs should adopt this workflow of committing changes to the tests in the same commit as the spec changes, so a submodules approach could help us with that world. I dunno.

In any case, I don't have a specific timeline.

> Also, the current html tests are running regular tests, tests in worker, tests in shared worker and tests in service worker. Would it be possible to split them in xx.html, xx-worker.html, xx-sharedworker.html...? If that is ok, I can take over that editing.

I agree with the others that this would be a lot of work, and so I'd prefer the current form. I'd actually prefer if web platform tests took over this work for me, like they already do with .worker.js files... the boilerplate and duplication (e.g. between `<script>`s in .html + `if`-guarded `importScript`s in the .js) is annoying.

One issue right now is that I am getting warnings from testharness about how the tests all have the same name. That is, the worker tests and service worker tests and shared worker tests and non-worker tests all just call `test(..., 'name')` so when you run them all together you get four tests with the same name. I am not sure what the right way to fix this is. Maybe @jgraham has some ideas.

@wanderview

> I could get these tests into wpt repo as one of my first tasks. 

Less work for me! Sounds great :)

**Comment by youennf** [comment]
I just did a quick check in WebKit.

Having service-worker tests within the same file is kind of ok.
It does not disrupt other tests.
The service-worker "FAIL" test line is not at the end but before worker test lines which is a bit misleading for users.
Also as noted by @domenic, having the same names for different test variations is also misleading.

The SharedWorker tests are disrupting as the exception in case SharedWorker is not defined is caught too late.

If all above issues are fixed, a single test file sounds ok to me.
Fixing the SharedWorker (and Worker as well I guess) would be a prerequisite though.

**Comment by youennf** [comment]
Given the latest test updates, the tests should be able to land in WebKit.
Plan is to land them in "web-platform-tests/streams-api", which I guess will be the folder name in W3C wpt repo.

**Comment by calvaris** [comment]
We are landing them now: https://bugs.webkit.org/show_bug.cgi?id=152051.

**Comment by wanderview** [comment]
@youennf @calvaris Is there any reason you put the tests under /streams-api instead of just /streams in webkit?

@yurydelendik and I would like to land the tests under just /streams.  Its more consistent with the majority of directory names in wpt.  Also, in my experience we end up typing this a lot during development/testing, so it would be nice to avoid unnecessary chars in the name.

Is that going to cause you guys any angst?

**Comment by youennf** [comment]
Great to hear that news, that will ease WebKit/wpt resync. 
No problem to use streams instead of streams-api.

**Comment by youennf** [comment]
On another point, there are some test utils routines in resources folder. They are not streams related. Maybe it is worth moving this out of streams folder?

**Comment by wanderview** [comment]
Lets get the tests uplifted first and then we can use PRs on the wpt repo to tweak things like that.  Sound reasonable?

The tests are going to land in gecko tree first and then our automated tools will uplift to wpt repo.

**Comment by youennf** [comment]
Sounds good.
