### ISSUE TITLE
node streams coordination

### ISSUE THREAD

**Issue by calvinmetcalf** [whatwg/streams#435]
The nodejs streams working group is planing on having a working group meeting tentatively scheduled for next Monday (nodejs/readable-stream#183) and anyone working on whatwg streams who wants to is more then welcome to join the meeting. The streams WG would really benefit to know, what is nailed down vs what is still up in the air on your end and to get your perspective on how problems we need to solve in node streams were solved in whatwg streams.

**Comment by domenic** [comment]
Sorry for the delay in getting back to you on this. At this point:

- Readable streams are looking very solid. The new byte stream aspects perhaps a little less so, due to lack of implementer experience, but we're very happy with the design.
- Writable streams are lagging behind. They need several updates to align with the lessons learned during the design of readable streams, such as the need for exclusive locking.
- Transform streams are blocked on writable streams (as we still believe the best design for them is a { readable, writable } pair).

As for how problems were solved differently, https://github.com/whatwg/streams/blob/master/FAQ.md#what-are-the-main-differences-between-these-streams-and-nodejs-streams gives some idea.

Happy to continue discussing more if desired.
