### ISSUE TITLE
Convert internal slot accesses in the reference implementation to use symbols

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#443]
/cc @yutakahirano

@domenic

Sorry if it's already on your TODO list and noted in some other issue.

The V8 extra Chromium implementation you've authored is using internal symbols to access internal slots. Maybe this would benefit other vendors, too. Shall we just change the reference implementation to adopt the same way?

**Comment by domenic** [comment]
I'd be OK with this, although I don't think it gives very much benefit (since JS doesn't have private symbols like V8 does). Let me finish a refactoring I am working on though; I will ping this thread when I do so.

**Comment by domenic** [comment]
The refactoring I was referring to is up at #444. The reference implementation is not very much affected in the end.

**Comment by tyoshino** [comment]
@wandereview Ben, does this benefit you?

**Comment by wanderview** [comment]
I'm not sure what v8 private symbols are.  In spidermonkey we always access internal slots via an integer index.  The code in our tree uses a name for the constant, but these are converted and the shipped code only has integers.  So we have no real way to do things like "if object has slot FooBarBaz", because different object constants could make to the same integer.

What do v8 private symbols do?

**Comment by tschneidereit** [comment]
> So we have no real way to do things like "if object has slot FooBarBaz", because different object constants could make to the same integer.

Well, we do have that, by doing class checks internally. E.g. if the spec has us do things such as `If x does not have a [[PromiseState]] internal slot, return false`, we don't just check if the object has the right size, we check the (internal) class associated with it, which in turn means that it has the expected memory layout, too, so the integer index for a slot, combined with this check, is equivalent to v8's use of private symbols.

**Comment by bzbarsky** [comment]
One thing, though: using things like `Symbol('[[Cancel]]')` in the reference implementation means that the reference implementation and the spec will in fact have different behavior, no?  In particular, the reference implementation will leak its stuff via `Object.getOwnPropertySymbols` and the spec will not.

It's not clear what the goal of the reference implementation is, but if the goal is that it be a correct implementation of the spec while being valid ES6, then I expect the only reasonable way to implement the spec concept of internal slots is via weakmaps that are never exposed directly.

**Comment by tyoshino** [comment]
> We mainly look at the spec text directly.

Thanks, @wanderview. Then, this doesn't benefit you.

----

For clarification, Let me split the proposal into two smaller proposals:

1. define constant at the top and access properties using the constants
1. use symbols for the constants

Even just (1) makes it easier to sync our impl w/ reference impl.

----

@bzbarsky Oh, good point. We don't intend to leak the identifiers. It might be just misleading and we might want to just align with others i.e. using `._foobar` property accesses or using weakmaps as you suggested to implement internal slot accesses in the spec.

**Comment by domenic** [comment]
The intent of the reference implementation is to help validate spec changes and build the test suite, not to be 100% faithful. It's true there are observable differences, but unless those differences get in the way of writing good tests or editing the spec, they don't really matter.

**Comment by tyoshino** [comment]
Hmm, ok. So, for now, I'll refrain from defining constants and keep the impl simple.

**Comment by bzbarsky** [comment]
I suggest not calling it a reference implementation if it's not intended to actually implement the spec correctly.  Typically a reference implementation means something that can be used for black-box comparisons against other implementations and expresses the intent of the spec in cases where the spec is ambiguous (see items 4 and 5 in the list at https://en.wikipedia.org/wiki/Reference_implementation>).  It sounds like you have something that covers itsms 1-3, but not 4 and 5.

**Comment by domenic** [comment]
I think it covers those points very well, as long as you don't probe at certain edge cases related to the JavaScript object model and unrelated to streams. In particular it fulfills those purposes perfectly for all the *algorithms* in the spec.

**Comment by bzbarsky** [comment]
I think we may have to agree to disagree here...  

I also think we should have tests in the test suite that _do_ poke those edge cases of the object model to make sure UA implementations don't take shortcuts they're not supposed to take.

**Comment by mpotra** [comment]
In my JS implementation I started with Symbols right from the beginning. The reason is that symbol properties do not end up in any serialization, such as JSON.

However, I think this choice is up to the implementors, and the spec shouldn't force this in any way, given that each platform has its own optimal way of defining and using internal properties.

Also, compliance shouldn't validate on internal properties, not even in tests. Deeper tests, that touch internal symbols should be kept per implementation.

My intention is to improve the performance of my JS implementation, and as such I might end up with re-ordering internal properties and algorithms.

As long as any implementation yields the same behavior, on the public methods and properties, I'd say there's greater benefit to allowing internals (properties and algos) up to the implementors. The goal is having a uniform set of interfaces and objects, that consumers can use regardless of the implementation.
Forcing this type of definitions on implementations might make it more difficult or sub-optimal for other implementations. E.g. using JS symbols in a C/C++ implementation is slower than using native un-exposed properties.

**Comment by domenic** [comment]
Let's be very clear: any implementation that uses underscored properties, or symbols, is not compliant with the spec. The spec mandates using ECMAScript "internal slots", which means that if you do `Object.getOwnPropertyNames`, `Object.getOwnPropertySymbols`, or any other reflective API, no internal slot-like properties should show up. So @mpotra, your implementation is not compliant with the spec, similar to the reference implementation in this repo, as we've discussed above.

Also as discussed above, that doesn't mean that those implementations aren't _useful_. But they certainly aren't 100% _spec-compliant_.
