### ISSUE TITLE
Should write() always error the stream when it rejects the promise it returned?

### ISSUE THREAD

**Issue by tyoshino** [whatwg/streams#476]
writer.closed rejects when some error occurs in the writable stream. And therefore, those who're not interested in timing of successful completion of each write() but only interested in any error event may write() and forget but just watch writer.closed.

BYOB read() method has a logic that validates the argument and returns a rejected promise without erroring the stream when the validation fails. If we introduce similar logic to write(), the write()-and-forget() described above won't work.

Is this implying that such no-erroring rejection is bad design?

**Comment by domenic** [comment]
Hmm, interesting. I think the BYOB design is good... it tries to distinguish between two types of errors:

- This particular chunk is bad and I won't allow it.
- I tried to write, but doing so failed, and you probably should not try again; treat this as broken.

I guess right now we do not support this distinction very well in the underlying sink/controller API. For example, let's say you wanted to implement a writable stream that only accepted strings, or bytes, or something. I think it would be good to reject a particular write, without necessarily killing the entire writable stream. But right now all you can do is return a rejected promise, which will cause the stream to become errored.

I see a few options:

- Say that if you fail validation, we should just error the whole stream. Probably for BYOB read() too. You screwed up and you don't get to recover. This is nice and simple, at least.
- Allow separate validation and erroring capabilities.  I guess the most natural way to do this is to say that returning a rejected promise from write() does not error the stream, and you have to do that with a separate controller.error() call?

There is also a gray area. If a write fails, not because of the producer's fault, but because of some transient issue, then it is simpler to error the stream---we probably should not let them continue writing, as they might skip a chunk that's important.

Hmm, that kind of logic is moving me more toward the "error the whole stream" option. E.g. consider if you had a program error that somehow ended up with chunks [string1, string2, blob3, string4, string5]. Probably it would be better to write string1 + string2 then get an errored writable stream, than to write string1 + string2 + string4 + string5 and only get the error notification on the one write.

Also, part of this comes down to, what do the underlying sink APIs look like? Looking through http://man7.org/linux/man-pages/man2/write.2.html#ERRORS it seems to me like most of these are not recoverable.

So for writable streams error-forever may be better. For BYOB it seems a bit less clear since I don't think there's the possibility of that kind of skipping and of missing error notifications. So maybe the asymmetry is OK?

**Comment by tyoshino** [comment]
> Allow separate validation and erroring capabilities. I guess the most natural way to do this is to say that returning a rejected promise from write() does not error the stream, and you have to do that with a separate controller.error() call?

Oh, interesting. But me too leaning toward error-the-whole option unless we come up with API with better distinction.

> For BYOB it seems a bit less clear since I don't think there's the possibility of that kind of skipping and of missing error notifications. So maybe the asymmetry is OK?

I see. Given that multiple outstanding read() is less useful than multiple outstanding (queued) write() in general.

**Comment by domenic** [comment]
@tyoshino do you have any thoughts on this issue after some time? It looks like we were leaning toward one of two options:

1. Close it and do nothing.
2. Also modify BYOB readable streams so that enqueuing a bad chunk errors the stream. In this case we should rename the issue and update its labels.

**Comment by ricea** [comment]
I am in favour of option 1.

**Comment by domenic** [comment]
Let's do it. Happy to reopen upon further discussion.
