### ISSUE TITLE
"Set totalSize to totalSize + pair.[[size]]."

### ISSUE THREAD

**Issue by ricea** [whatwg/streams#582]
https://streams.spec.whatwg.org/#get-total-queue-size

> Set totalSize to totalSize \+ pair\.\[\[size\]\]\.

Maybe there should be a note here that this algorithm can't be used as-is because it results in O(N^2) behaviour? I just tripped over this myself.

**Comment by domenic** [comment]
That's what's intended by https://streams.spec.whatwg.org/#queue-with-sizes:

> although in implementations it would of course be backed by a more efficient data structure

But maybe we could make it more prominent with a `<div class="warning">` in the problematic algorithm in particular. Or even just overhaul the whole thing to actually be efficient.

**Comment by isonmad** [comment]
One thing I don't get is the inconsistency between byte queues and non byte queues. Bytestream controllers have [[totalQueuedBytes]], which is constantly updated, but the default controller uses GetTotalQueueSize, and the reference implementation doesn't even follow that as-written and keeps a running total like bytestream controllers do, because it's more efficient.

Shouldn't both be either one or the other?

**Comment by ricea** [comment]
Thanks @isonmad, I hadn't noticed that byte queues already do the right thing. It doesn't seem like we're gaining much in terms of readability by doing the wrong thing for non-byte queues.

The reference implementation tracks the size by adding a `.totalSize` attribute to the Array holding the queue. We can't standardise that. The Chrome implementation uses a separate [[queueSize]] internal slot on the controller, which works, but I got confused between queue _size_ and queue _length_ when I was implementing it. I think we need a different name.

The [[totalQueuedBytes]] name used by byte queues is also unsuitable, but maybe [[totalQueuedSize]] is clear enough.

Bikeshedding welcome.

**Comment by tyoshino** [comment]
We just built the spec text of the byte stream by translating the reference implementation without paying attention to this point. I don't quite remember but the fact the record used for the byte stream (see ReadableByteStreamControllerEnqueueChunkToQueue()) is different from the one for the non-byte stream and that chunks of the byte stream can be partially consumed might have made me reluctant to think about the consistency.

`totalQueuedSize` sounds ok.

**Comment by isonmad** [comment]
Wait, isn't there a reason you'd want to spec it as adding up the numbers every time for the case where each size can return an arbitrary Number, if not implement it?

Like if the size starts to exceed `Number.MAX_SAFE_INTEGER`, could subtracting one chunk's size from the total end up not the same result as adding up all remaining chunks again.

**Comment by ricea** [comment]
Thanks @isonmad. I hadn't realised the difference was observable.

However, we can't implement it as adding the numbers every time because of the performance issue. Either we keep a running count or we do something cleverer to deal with the lack of precision issue you mentioned.

For example, we could keep a running count but recalculate it every time removing a chunk results in the number of remaining chunks being a power of two. However, that would be very janky.

**Comment by ricea** [comment]
My current thinking is to use a running total normally, but switch to summing when totalSize becomes negative or the number of records in _queue_ is less than 8 (or some other arbitrary small number).

**Comment by domenic** [comment]
To me this is a good argument for codifying the "shortcut" (what the reference implementation does) in the spec. It doesn't seem important to me to support arbitrary precision arithmetic, where the size gets larger than MAX_SAFE_INTEGER or the chunk sizes are very small or similar. Maybe we should even specify that the arithmetic should be performed as double-precision.

It's also worth noting that in general we're allowed to fail to follow the spec when things grow out of bounds. E.g., in the extreme case, we're allowed to crash with out of memory errors. This seems somewhat analogous.

**Comment by tschneidereit** [comment]
I agree that codifying the shortcut makes the most sense. If people are really concerned about the corner cases, we could add checks to `DequeueValue` and recalculate the cached total size if it becomes negative or is `MAX_SAFE_INTEGER` before subtracting the dequeue'd value's size. I don't think that that's required though, mostly because all implementations will end up behaving in the same way in these situations.

**Comment by tyoshino** [comment]
Great catch, isonmad!

Thank you ricea for trying to figure out a good workaround. But I basically agree with domenic. We should have some note about the caveats of possible overflow, digit loss, etc. in the spec (and encourage use of integers for precise processing?), and just use the shortcut algorithm.

**Comment by ricea** [comment]
For the record, there are three "reasonable" expectations about desiredSize that I have been considering:

1. desiredSize = HWM - (total size of chunks in queue), subject to rounding errors.
2. desiredSize - HWM == exactly 0 when the queue is empty.
3. desiredSize monotonically decreases as long as there are no calls to read(), and monotonically increases as long as there are no calls to enqueue().

The current specced behaviour satisfies all three expectations (there are rounding errors in 1., but they conform exactly to expectations).

The running total behaviour as implemented in the reference implementation and Chromium satisfies expectation 3, can have unexpected rounding errors on 1. and fails 2. when the size of the chunks varies by a very large magnitude.

The workaround I proposed above can fail 3., can have unexpected rounding errors in 1 and passes 2.

Resetting to zero when the queue becomes empty also can fail 3., have unexpected rounding errors in 1 and passes 2.

I find myself flip-flopping between two positions:
1. Any of these is fine. If you have extreme variations in chunk size then you're going to have a bad time. This being the case, we should stick with the running total behaviour.
2. Having desiredSize != HWM with an empty queue is just too weird, and so we should switch to "reset to zero" behaviour.

**Comment by tyoshino** [comment]
Nice analysis.

Yeah, failing to satisfy expectation (2) would look very weird, but not yet well convinced if we should take care of that.

Regarding expectation (1), maybe it's great if `desiredSize < strict calculation of HWM - (total size)` holds, given the purpose of desiredSize, but ... it would also require some complicated rounding logic.

I basically agree with the position (1) now. We just warn that opting-in non-integer size would take you to a wonderland.

**Comment by domenic** [comment]
@tschneidereit we haven't explicitly forbidden negative sizes (yet?). We could add a check every time we call the size function, but we don't have one right now. I think most of your pose assumes nonnegative sizes.

---

My personal conflict is that I lean toward "Any of these is fine." and then I look at the code and see that we have these two coupled variables, [[queue]] and [[queueTotalSize]], and we only reset one of them. That seems wrong. So that's why I introduced ResetQueue.

I think introducing something like ResetQueue is necessary since otherwise when you empty the queue you could still have a desiredSize of 5. No rounding errors involved, just enqueue 2, enqueue 3, error the stream. Queue is empty and desiredSize is 5. Not great. Maybe we could just claim that desiredSize is meaningless when the stream is closed or errored?

Or maybe we should ape writable streams and set it to null!! That actually sounds better. Let's do that.

With that resolution in mind, I think setting it to null on closed/errored and then just leaving it alone for empty is fine. That doesn't get us many expectations but "anything is fine" IMO :)

**Comment by tschneidereit** [comment]
> @tschneidereit we haven't explicitly forbidden negative sizes (yet?). We could add a check every time we call the size function, but we don't have one right now. I think most of your pose assumes nonnegative sizes.

I had assumed that mostly because we're throwing a RangeError if any enqueued item has a negative size.

I just realize that `NaN` is the more serious issue: any one item being enqueued can "infect" the queue, and that actually seems like a plausible bug in content code to me. What exactly would be the problem with adding a simple check to `GetTotalQueueSize`? In light of `NaN` perhaps `if (IsFiniteNonNegativeNumber(size)) return size else return 0`.

> I think introducing something like ResetQueue is necessary since otherwise when you empty the queue you could still have a desiredSize of 5.

Agreed.

**Comment by domenic** [comment]
> I had assumed that mostly because we're throwing a RangeError if any enqueued item has a negative size.

Oh, wow, I seem to have forgotten about that. OK, yes, we are prohibiting negative (and NaN, and Infinity) sizes. So such chunks will not make it into the queue. Phew!

**Comment by domenic** [comment]
I've updated #611 to:

- Use ResetQueue everywhere to satisfy my sense that queue and queueTotalSize should be kept in sync.
- Make desiredSize always return 0 for closed streams and null for errored streams. Because of this, the above change is unobservable, I believe.

I'm also moving the tests to a WPT pull request which I will edit #611 to link to.

**Comment by domenic** [comment]
Ping for review on #661 (which is now rebased) and the corresponding WPT PR https://github.com/w3c/web-platform-tests/pull/4568.
