### ISSUE TITLE
Should ReadableStreamDefaultReader be exposed?

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/streams#586]
The spec doesn't seem to cover which classes should be exposed where.

Right now `ReadableStreamDefaultReader` isn't exposed on the global. Should it be? Feels like it should be exposed somewhere for extensibility.

**Comment by ricea** [comment]
It's cunningly hidden here: https://streams.spec.whatwg.org/#globals

If I was King Of The World I would explicitly mention it alongside each class definition as well.

You can get it by doing something like

```javascript
const ReadableStreamDefaultReader = new ReadableStream().getReader().constructor;
```

If there's a compelling use case for subclassing it then certainly it could be exposed.

**Comment by jakearchibald** [comment]
Hah, yes, I missed that bit because I was looking for it alongside the class definition, but that's just where I'm used to seeing it on other specs.

The above code is exactly what I used to get at the constructor. My usecase was adding `Symbol.asyncIterator`. I realise now's not the time for polyfills like this, but it might be in future.

**Comment by domenic** [comment]
This is a conflict between ECMAScript style (expose only top-level classes) and web-style (expose everything). I've erred on the conservative side for now, since we can only go in one direction. The argument for exposing everything is, of course, this type of monkeypatching and polyfilling and instanceof testing and so on. I'm hesitant to do so before we hear more people wishing for it, but this is a good data point...

**Comment by ricea** [comment]
It turns out that switching to WebIDL (#963) makes the answer to this question "yes". WebIDL doesn't allow an type that is not exposed to be constructible. From https://heycam.github.io/webidl/#NoInterfaceObject:

> If the [NoInterfaceObject] extended attribute is specified on an interface, then the [Constructor] extended attribute must not also be specified on that interface. A [NamedConstructor] extended attribute is fine, however.
