### ISSUE TITLE
[Question] I created a project that explains the spec

### ISSUE THREAD

**Issue by TejasQ** [whatwg/streams#848]
This is just a question: [I created a project that serves as an introduction to this spec](https://github.com/TejasQ/basically-streams) for newer developers to it. I was wondering if I could add my demos to this repository, or link to it somehow? All of this in the effort to make knowledge of this more widespread, of course.

**Comment by ricea** [comment]
Great demos! It's really valuable to have this kind of introductory material so that developers can pick up streams easily. I really liked the clear comments in the source explaining the steps.

I hope when [transform streams](https://streams.spec.whatwg.org/branch-snapshots/transform-stream-standard-text/#ts) are standardised and available in browsers you'll be able to add some demos for them too.

I think we could add a link to these demos to https://streams.spec.whatwg.org/demos/. What do you think, @domenic?

**Comment by TejasQ** [comment]
Awesome! Thanks for the response, consideration, and the enhancement issues on my project, @ricea! I have implemented all of them. 🎉 

Man, I love Open Source.

**Comment by TejasQ** [comment]
[I went a little nuts and built an entire (small) PWA around this spec](https://github.com/TejasQ/basically-streams/tree/master/examples/streaming-pwa), complete with offline and the works.

**Comment by domenic** [comment]
Great stuff @TejasQ! Glad we could add links to your demos in #853 :)
