### ISSUE TITLE
[Question] questions about streaming-element-backpressure.js

### ISSUE THREAD

**Issue by abdulhannanali** [whatwg/streams#855]
I was working on a new demo that demonstrates a real world usage of streams i.e. translating the text to emojis with the help of TransformStream and then displaying it on the UI. There's something that might help this application in reducing the jank which is happening because of transforming and writing large amounts of text.

An example in the demo might help, but I am confused about some lines and would love if anyone can clarify them.

https://github.com/whatwg/streams/blob/99ffba7a632c261566c12da60bb35800a42e3b3f/demos/tags/streaming-element-backpressure.js#L68-L72

What purpose does this serve at the start, I guess this `if` conditional is going to be executed only one time. Can we move this logic within the `start` function of writable stream too, since it seems to mean waiting out any frame that's to be executed first. 

2. Why are we writing into `iframe`, is it for performance reasons? 
https://github.com/whatwg/streams/blob/99ffba7a632c261566c12da60bb35800a42e3b3f/demos/tags/streaming-element-backpressure.js#L26-L39

**Note: I apologize if this is the wrong place to ask questions about. I was clueless and thought about asking the repo owners and maintainers directly**

**Comment by ricea** [comment]
1. The reason this is at the beginning of write() is that start() is called when the element is created, which may be a long time before data actually starts streaming. The algorithm works by measuring the time between displayed frames and comparing it to its target of 33ms. It then adjusts the number of characters it processes at a time to try to hit the target. startNewChunk() has the effect of resetting the timer, so if it was called a long time before the first write() the measurement of the first frame would be wrong. Is there a way I could make this clearer to someone reading the code? One way to avoid the delay on the first frame would be to make a first chunks a special case. I was trying to make the code as simple as possible, so it is not optimised.
2. Writing into an iframe allows us to use document.write() to use the browser's streaming parser. I adapted this from code written by Jake Archibald, who wrote more about the technique here: https://jakearchibald.com/2016/fun-hacks-faster-content/. Compared to appending to innerHTML it means that only the new chunks need to be parsed, rather than all the HTML needed to be re-parsed for every new chunk of data. The main reason for doing it this way is to get as close to streaming HTML parsing as is possible in current browsers, but I expect the performance is good too.

This is a good place to ask about the demos.

**Comment by abdulhannanali** [comment]
@ricea First of all sorry for the delay in replying, meanwhile I was learning about `requestAnimationFrame` whenever I found some time. 

Regarding the first one, the usage of `requestAnimationFrame` API seems a bit confusing in this application. The point of this api is to execute a set of statements that make changes to the pixels in some way before the next browser repaint, this will keep the animations in the browser synchronized and jank free giving us an abstraction to keep our application synchronized with the actual frame rate. However, it  seems to be the case that our usage of this API is entirely reverse of what was intended, do you think the following statements should move to the top 
https://github.com/whatwg/streams/blob/99ffba7a632c261566c12da60bb35800a42e3b3f/demos/tags/streaming-element-backpressure.js#L82-L84 right before we actually need to write the chunk to the iframe. https://github.com/whatwg/streams/blob/99ffba7a632c261566c12da60bb35800a42e3b3f/demos/tags/streaming-element-backpressure.js#L78

This would provide better result about the time it actually takes to execute the complete callback (and paint the result to the screen, not clear about this though).

`requestAnimationFrame` also seems to be providing a top level api, which can be significantly throttled down based on certain factors depending on the user agent such as the tab focus. In that case, would the logic we mention here still calculate appropriate number of chunks we want to write? Based on the wait time, it can even fall down to like 4 characters per frame, which will take some time to recover since there seems to be a limit of `3` for the frames to smooth over.

**Comment by abdulhannanali** [comment]
@ricea Nice trick, I did not know that we can use the streaming parser this way, can definitely see good uses for it in order to load large documents with the help of streams. In the previous demos I created, I create a span element with the chunk as content and then append it to the container. Does this span approach have any drawbacks? using innerHTML for large documents with streaming is definitely the worst nightmare.

**Comment by ricea** [comment]
@abdulhannanali You are right, I am abusing `requestAnimationFrame` to get an approximate idea of when the browser is ready to receive more HTML without janking. It's unfortunate this is confusing. I was trying to create a simple example of using backpressure to avoid jank. Because each chunk of the table takes longer to layout that the previous one, using a fixed chunk size and delay gave very poor results.

I experienced the issue with the chunk size become incredibly small during my tests, which is why I put in this hack:
https://github.com/whatwg/streams/blob/99ffba7a632c261566c12da60bb35800a42e3b3f/demos/tags/streaming-element-backpressure.js#L90
to keep the chunk size at 256 or larger.

`MS_PER_FRAME`, the minimum chunk size and `FRAMES_TO_SMOOTH_OVER` are all hacks to make it possible to do this with a very simple algorithm.

`startNewChunk` doesn't reset a timer explicitly, but it does implicitly reset the "frame timer" by changing how long the following call to `startNewChunk` will take.

The fundamental issue is that the browser doesn't provide an answer to the question "how much HTML can I render right now without causing jank?" So we have to use an approximation. It's certainly possible to create a far better approximation than this demo uses, but it would distract from the main point of the demo.

If you can find a way to make it easier to understand without making it longer or making the jank or load time worse, then please send a pull request. But don't worry too much about it.

---

Creating a span for each chunk is a cleaner method as it doesn't require strange hacks with iframes. However, it won't work if the chunks contain HTML tags because they can get split between spans. So the iframe hack is more general.
