### ISSUE TITLE
Propagate errors from writableStream.abort(reason)

### ISSUE THREAD

**Issue by domenic** [whatwg/streams#896]
This was removed from the spec, in favor of making the [[storedError]] after abort always a TypeError. I believe this was because previously sometimes we had to synthesize a TypeError anyway, and we thought it would be best to be uniform. We should dig into the commit history to find out.

We should reverse this decision, and add back error propagation. This is crucial, in particular, for transform streams. https://github.com/whatwg/streams/pull/847 contains some examples whose results are surprising without this propagation.

**Comment by domenic** [comment]
I found the original thread; digesting now: https://github.com/whatwg/streams/issues/464

One alterative it brings up is having pipeTo do error propagation, even if abort() does not. That would mean using e.g. WritableStreamDefaultControllerError instead of WritableStreamAbort. That's a bit of a layering violation in our current setup because currently only the creator of the writable stream can use WritableStreamDefaultControllerError. But maybe we can rearrange things to justify to ourselves.

**Comment by ricea** [comment]
I am in favour of just changing the behaviour to "[[storedError]] is set to _reason_", rather than adding special cases. I am preparing a change to do that now.

This also means changing what happens to readable's [[storedError]] when `abort(reason)` is called on the writable side of a TransformStream. I am changing it the same way so it will match the writable side.
